Repository treehouses/builder, pull requests merged in 2020-07, with the labels that each got.

#773 update `autorunonce` enterprise and hidden networks (fixes #770)
  autorunonce
Labels: please review

#794 add shadowsocks and proxychains4 (fixes #793)
  scripts.d/16_pkg_install.sh
Labels: priority, ready

#806 builder: download over aria2c with lpd and dht (fixes #805)
  builder
Labels: enhancement
