Repository treehouses/builder, pull requests merged in 2020-05, with the labels that each got.

#690 update `30_ssh_keys.py` (fixes #684)
  scripts.d/30_ssh_keys.py
Labels: please review

#701 update .travis.yml (fixes #700)
  .travis.yml
Labels: please review, priority

#702 add gh (fixes #699) (fixes #686)
  .travis.yml
  builder
  scripts.d/20_gh.sh
Labels: please review, priority

#715 update `builder` (fixes #708)
  builder
Labels: please review, testing

#714 update `Vagrantfile` (fixes #713)
  Vagrantfile
Labels: please review, priority, testing

#693 add uptimed package and disable service
  scripts.d/16_pkg_install.sh
  scripts.d/35_disable_uptimed.sh
Labels: please review, testing
